package WellLanguage.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.workbench.action.ActionAccess;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import javax.swing.JOptionPane;

public class RunPythonScript_Action extends BaseAction {
  private static final Icon ICON = IconContainer.ICON_a0;

  public RunPythonScript_Action() {
    super("Run Python Script", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setActionAccess(ActionAccess.UNDO_PROJECT);
    updateInBackground(true);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    ProcessBuilder pb = new ProcessBuilder("bash", "");

    JOptionPane.showMessageDialog(null, "Generate Python");
  }
}
