package WellLanguage.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.BoxLayout;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import WellLanguage.util.HtmlTag;

public class BN555__ {
  private static String path = "";
  public static void main(String[] args) {
    gui();
  }
  public static void gui() {
    JFrame frame = new JFrame("Choose where to export the Project");
    frame.setSize(300, 200);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    JButton folderButton = new JButton("Select Folder");
    final JTextField folderPathField = new JTextField();
    folderPathField.setEditable(false);
    JButton actionButton = new JButton("Export HTML");
    frame.setLayout(new BoxLayout(frame.getContentPane(), BoxLayout.Y_AXIS));
    frame.add(folderButton);
    frame.add(folderPathField);
    frame.add(actionButton);
    folderButton.addActionListener((ev) -> selectFolder(folderPathField));
    actionButton.addActionListener((ev) -> triggerAction(folderPathField.getText()));
    frame.setVisible(true);
  }
  private static void selectFolder(JTextField folderPathField) {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnValue = chooser.showOpenDialog(null);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
      folderPathField.setText(chooser.getSelectedFile().getAbsolutePath());
      path = chooser.getSelectedFile().getAbsolutePath();
    }
  }
  private static void triggerAction(String folderPath) {
    if (folderPath.isEmpty()) {
      JOptionPane.showMessageDialog(null, "No folder selected!", "Warning", JOptionPane.WARNING_MESSAGE);
    } else {
      writeToHtml(map_ActivityBoard.generateActivitiesHtml(), path + "/" + "TableroActividades" + ".html");
      writeToHtml(map_MotorTable.generateMotorTableHtml(), path + "/" + "TablaMotores" + ".html");
      writeToHtml(generateWellHtml(), path + "/" + "BN555" + ".html");
      writeToHtml(generateIndex(), path + "/index" + ".html");
      writeToHtml(map_WorkersTable.generateWorkersTableHtml(), path + "/" + "Tabla_de_Empleados" + ".html");
      JOptionPane.showMessageDialog(null, "Saved to: " + folderPath, "Folder Path", JOptionPane.INFORMATION_MESSAGE);
    }
  }
  public static void writeToHtml(StringBuilder flow, String name) {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(name))) {
      writer.append(flow.toString());
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }
  public static StringBuilder generateIndex() {
    StringBuilder html = new StringBuilder(HtmlTag.DOCTYPE);
    html.append(HtmlTag.HTML_OPEN);
    html.append(HtmlTag.HEAD_OPEN);
    html.append(HtmlTag.META);
    html.append(HtmlTag.TITLE_OPEN);
    html.append("Welcome - Wells Report");
    html.append(HtmlTag.TITLE_CLOSE);
    html.append(HtmlTag.STYLE_OPEN);
    html.append(HtmlTag.CSS_STYLE);
    html.append(HtmlTag.STYLE_CLOSE);
    html.append(HtmlTag.HEAD_CLOSE);
    html.append(HtmlTag.BODY_OPEN);
    html.append(HtmlTag.HEADER_OPEN);
    html.append(HtmlTag.hTagFormat(1, "Wells Report"));
    html.append(HtmlTag.NAV_OPEN);
    html.append(HtmlTag.UL_OPEN);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("index" + ".html", "home"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("TableroActividades" + ".html", "TableroActividades"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("TablaMotores" + ".html", "TablaMotores"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("BN122" + ".html", "BN122"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("BN555" + ".html", "BN555"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("Tabla_de_Empleados" + ".html", "Tabla de Empleados"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.UL_CLOSE);
    html.append(HtmlTag.NAV_CLOSE);
    html.append(HtmlTag.HEADER_CLOSE);
    html.append(HtmlTag.BODY_CLOSE);
    html.append(HtmlTag.HTML_CLOSE);
    return html;
  }
  public static StringBuilder generateWellHtml() {
    StringBuilder html = new StringBuilder(HtmlTag.DOCTYPE);
    html.append(HtmlTag.HTML_OPEN);
    html.append(HtmlTag.HEAD_OPEN);
    html.append(HtmlTag.META);
    html.append(HtmlTag.TITLE_OPEN);
    html.append("BN555");
    html.append(HtmlTag.TITLE_CLOSE);
    html.append(HtmlTag.STYLE_OPEN);
    html.append(HtmlTag.CSS_STYLE);
    html.append(HtmlTag.STYLE_CLOSE);
    html.append(HtmlTag.HEAD_CLOSE);
    html.append(HtmlTag.BODY_OPEN);
    html.append(HtmlTag.HEADER_OPEN);
    html.append(HtmlTag.hTagFormat(1, "BN555"));
    html.append(HtmlTag.NAV_OPEN);
    html.append(HtmlTag.UL_OPEN);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("index" + ".html", "home"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("TableroActividades" + ".html", "TableroActividades"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("TablaMotores" + ".html", "TablaMotores"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("BN122" + ".html", "BN122"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("BN555" + ".html", "BN555"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append(HtmlTag.linkFormat("Tabla_de_Empleados" + ".html", "Tabla de Empleados"));
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.UL_CLOSE);
    html.append(HtmlTag.NAV_CLOSE);
    html.append(HtmlTag.HEADER_CLOSE);
    html.append(HtmlTag.hTagFormat(1, "BN555"));
    html.append(HtmlTag.BR);
    html.append(HtmlTag.DIV_OPEN);
    html.append(HtmlTag.hTagFormat(3, "0.01"));
    html.append(HtmlTag.BR);
    html.append(HtmlTag.P_OPEN);
    html.append("2-2-2002");
    html.append(HtmlTag.P_CLOSE);
    html.append(HtmlTag.BR);
    html.append(HtmlTag.UL_OPEN);
    html.append(HtmlTag.LI_OPEN);
    html.append("jorge");
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.LI_OPEN);
    html.append("luis");
    html.append(HtmlTag.LI_CLOSE);
    html.append(HtmlTag.UL_CLOSE);
    html.append(HtmlTag.BR);
    html.append(HtmlTag.P_OPEN);
    html.append("SGDFG");
    html.append(HtmlTag.P_CLOSE);
    html.append(HtmlTag.DIV_CLOSE);

    html.append(HtmlTag.BR);
    html.append(HtmlTag.DIV_OPEN);
    html.append(HtmlTag.hTagFormat(4, "Jorge"));
    html.append(HtmlTag.DIV_CLOSE);
    html.append(HtmlTag.BR);
    html.append(HtmlTag.hTagFormat(2, "Personnel"));
    html.append(HtmlTag.hTagFormat(3, "Team Name: Personnel"));
    html.append(HtmlTag.TABLE_OPEN);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.thTag("ID"));
    html.append(HtmlTag.thTag("Name"));
    html.append(HtmlTag.thTag("Role"));
    html.append(HtmlTag.thTag("Description"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.tdTag("1"));
    html.append(HtmlTag.tdTag("juan"));
    html.append(HtmlTag.tdTag("Ingeniero"));
    html.append(HtmlTag.tdTag("asfa"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TABLE_CLOSE);
    html.append(HtmlTag.BR);
    html.append(HtmlTag.coordinatesTag("4", "4", "5"));
    html.append(HtmlTag.BR);
    html.append(HtmlTag.hTagFormat(4, "Fluids"));
    html.append(HtmlTag.TABLE_OPEN);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.thTag("Oil Capacity"));
    html.append(HtmlTag.thTag("Water Capacity"));
    html.append(HtmlTag.thTag("Gas Capacity"));
    html.append(HtmlTag.thTag("Pressure"));
    html.append(HtmlTag.thTag("Gradient"));
    html.append(HtmlTag.thTag("Temperature"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.tdTag("2"));
    html.append(HtmlTag.tdTag("33"));
    html.append(HtmlTag.tdTag("4"));
    html.append(HtmlTag.tdTag("23"));
    html.append(HtmlTag.tdTag("43"));
    html.append(HtmlTag.tdTag("23"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TABLE_CLOSE);
    html.append(HtmlTag.BR);
    html.append(HtmlTag.hTagFormat(4, "Downhole"));
    html.append(HtmlTag.TABLE_OPEN);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.thTag("Top Perforation"));
    html.append(HtmlTag.thTag("Bottom Perforation"));
    html.append(HtmlTag.thTag("Pump Measured Depth"));
    html.append(HtmlTag.thTag("Pump Vertical Measured Depth"));
    html.append(HtmlTag.thTag("Anchor"));
    html.append(HtmlTag.thTag("PlugBack Total Depth"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.tdTag("234"));
    html.append(HtmlTag.tdTag("434"));
    html.append(HtmlTag.tdTag("32"));
    html.append(HtmlTag.tdTag("43"));
    html.append(HtmlTag.tdTag("342"));
    html.append(HtmlTag.tdTag("342"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TABLE_CLOSE);
    html.append(HtmlTag.BR);
    html.append(HtmlTag.hTagFormat(4, "Casing"));
    html.append(HtmlTag.TABLE_OPEN);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.thTag("Pressure"));
    html.append(HtmlTag.thTag("Cut"));
    html.append(HtmlTag.thTag("Surface Fluid Level"));
    html.append(HtmlTag.thTag("Pump Fluid Level"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TR_OPEN);
    html.append(HtmlTag.tdTag("234"));
    html.append(HtmlTag.tdTag("43"));
    html.append(HtmlTag.tdTag("23"));
    html.append(HtmlTag.tdTag("432"));
    html.append(HtmlTag.TR_CLOSE);
    html.append(HtmlTag.TABLE_CLOSE);
    html.append(HtmlTag.BR);
    html.append(HtmlTag.DIV_OPEN);
    html.append(HtmlTag.P_OPEN);
    html.append("Stroke: " + "3");
    html.append(HtmlTag.P_CLOSE);
    html.append(HtmlTag.P_OPEN);
    html.append("Rotation: " + "Counterclockwise");
    html.append(HtmlTag.P_CLOSE);
    html.append(HtmlTag.DIV_CLOSE);
    html.append(HtmlTag.BODY_CLOSE);
    html.append(HtmlTag.FOOTER_OPEN);
    html.append(HtmlTag.P_OPEN);
    html.append("Reporte generado el");
    html.append(HtmlTag.P_CLOSE);
    html.append(HtmlTag.FOOTER_CLOSE);
    html.append(HtmlTag.HTML_CLOSE);
    return html;
  }

}
