package WellLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.style.AbstractStyleClass;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.editor.runtime.descriptor.EditorBuilderEnvironment;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.MPSColors;

public class Styles_StyleSheet {
  public static class arialfontStyleClass extends AbstractStyleClass {
    public arialfontStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public arialfontStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.FONT_FAMILY, "Arial");
    }

  }
  public static class propertycolorStyleClass extends AbstractStyleClass {
    public propertycolorStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public propertycolorStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.orange));
    }

  }
}
