package WellLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_VolumeUnits extends EnumerationDescriptorBase {

  public EnumerationDescriptor_VolumeUnits() {
    super(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a3988c7aacL, "VolumeUnits", "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691542604460");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Liter_0 = new EnumerationDescriptor.MemberDescriptor("Liter", "L", 0x394a28a3988c7aadL, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691542604461");
  private final EnumerationDescriptor.MemberDescriptor myMember_CubicMeter_0 = new EnumerationDescriptor.MemberDescriptor("CubicMeter", "m3", 0x394a28a3988c7aaeL, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691542604462");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a3988c7aacL, 0x394a28a3988c7aadL, 0x394a28a3988c7aaeL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Liter_0, myMember_CubicMeter_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Liter":
        return myMember_Liter_0;
      case "CubicMeter":
        return myMember_CubicMeter_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
