package WellLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PumpUnitGeometry extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PumpUnitGeometry() {
    super(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b069L, "PumpUnitGeometry", "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784617");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Conventional_0 = new EnumerationDescriptor.MemberDescriptor("Conventional", "Conventional", 0x14a09e31149b06aL, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784618");
  private final EnumerationDescriptor.MemberDescriptor myMember_MarkII_0 = new EnumerationDescriptor.MemberDescriptor("MarkII", "MarkII", 0x14a09e31149b06cL, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784620");
  private final EnumerationDescriptor.MemberDescriptor myMember_TorqueMaster_0 = new EnumerationDescriptor.MemberDescriptor("TorqueMaster", "TorqueMaster", 0x14a09e31149b070L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784624");
  private final EnumerationDescriptor.MemberDescriptor myMember_AirBalance_0 = new EnumerationDescriptor.MemberDescriptor("AirBalance", "AirBalance", 0x14a09e31149b074L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784628");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b069L, 0x14a09e31149b06aL, 0x14a09e31149b06cL, 0x14a09e31149b070L, 0x14a09e31149b074L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Conventional_0, myMember_MarkII_0, myMember_TorqueMaster_0, myMember_AirBalance_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Conventional":
        return myMember_Conventional_0;
      case "MarkII":
        return myMember_MarkII_0;
      case "TorqueMaster":
        return myMember_TorqueMaster_0;
      case "AirBalance":
        return myMember_AirBalance_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
