package WellLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TempUnits extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TempUnits() {
    super(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a3988c6c47L, "TempUnits", "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691542600775");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Celsius_0 = new EnumerationDescriptor.MemberDescriptor("Celsius", "°C", 0x394a28a3988c6c48L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691542600776");
  private final EnumerationDescriptor.MemberDescriptor myMember_Farenheit_0 = new EnumerationDescriptor.MemberDescriptor("Farenheit", "°F", 0x394a28a3988c6c49L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691542600777");
  private final EnumerationDescriptor.MemberDescriptor myMember_Kelvin_0 = new EnumerationDescriptor.MemberDescriptor("Kelvin", "K", 0x394a28a3988c6c4dL, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691542600781");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a3988c6c47L, 0x394a28a3988c6c48L, 0x394a28a3988c6c49L, 0x394a28a3988c6c4dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Celsius_0, myMember_Farenheit_0, myMember_Kelvin_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Celsius":
        return myMember_Celsius_0;
      case "Farenheit":
        return myMember_Farenheit_0;
      case "Kelvin":
        return myMember_Kelvin_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
