package WellLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ActivityType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ActivityType() {
    super(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8dfabdef1L, "ActivityType", "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8076358177616813809");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Maintenance_0 = new EnumerationDescriptor.MemberDescriptor("Maintenance", "Maintenance", 0x7014fcf8dfabdef2L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8076358177616813810");
  private final EnumerationDescriptor.MemberDescriptor myMember_Offtime_0 = new EnumerationDescriptor.MemberDescriptor("Offtime", "Offtime", 0x7014fcf8dfabdf2fL, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8076358177616813871");
  private final EnumerationDescriptor.MemberDescriptor myMember_Inspection_0 = new EnumerationDescriptor.MemberDescriptor("Inspection", "Inspection", 0x7014fcf8dfabdf50L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8076358177616813904");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8dfabdef1L, 0x7014fcf8dfabdef2L, 0x7014fcf8dfabdf2fL, 0x7014fcf8dfabdf50L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Maintenance_0, myMember_Offtime_0, myMember_Inspection_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Maintenance":
        return myMember_Maintenance_0;
      case "Offtime":
        return myMember_Offtime_0;
      case "Inspection":
        return myMember_Inspection_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
