package WellLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Rotation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Rotation() {
    super(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7e18434ae3095a46L, "Rotation", "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/9086086237135657542");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Clockwise_0 = new EnumerationDescriptor.MemberDescriptor("Clockwise", "Clockwise", 0x7e18434ae3095a47L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/9086086237135657543");
  private final EnumerationDescriptor.MemberDescriptor myMember_Counterclockwise_0 = new EnumerationDescriptor.MemberDescriptor("Counterclockwise", "Counterclockwise", 0x7e18434ae3095a48L, "r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/9086086237135657544");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7e18434ae3095a46L, 0x7e18434ae3095a47L, 0x7e18434ae3095a48L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Clockwise_0, myMember_Counterclockwise_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Clockwise":
        return myMember_Clockwise_0;
      case "Counterclockwise":
        return myMember_Counterclockwise_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
