package WellLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActivitySchedule = createDescriptorForActivitySchedule();
  /*package*/ final ConceptDescriptor myConceptActivityTable = createDescriptorForActivityTable();
  /*package*/ final ConceptDescriptor myConceptCasingProperties = createDescriptorForCasingProperties();
  /*package*/ final ConceptDescriptor myConceptCoordinates = createDescriptorForCoordinates();
  /*package*/ final ConceptDescriptor myConceptDate = createDescriptorForDate();
  /*package*/ final ConceptDescriptor myConceptDepositWell = createDescriptorForDepositWell();
  /*package*/ final ConceptDescriptor myConceptDownhole = createDescriptorForDownhole();
  /*package*/ final ConceptDescriptor myConceptFluid = createDescriptorForFluid();
  /*package*/ final ConceptDescriptor myConceptHorizontalWell = createDescriptorForHorizontalWell();
  /*package*/ final ConceptDescriptor myConceptInjectionWell = createDescriptorForInjectionWell();
  /*package*/ final ConceptDescriptor myConceptInnerPesonel = createDescriptorForInnerPesonel();
  /*package*/ final ConceptDescriptor myConceptLengthWrapper = createDescriptorForLengthWrapper();
  /*package*/ final ConceptDescriptor myConceptMachinery = createDescriptorForMachinery();
  /*package*/ final ConceptDescriptor myConceptMetadata = createDescriptorForMetadata();
  /*package*/ final ConceptDescriptor myConceptMotor = createDescriptorForMotor();
  /*package*/ final ConceptDescriptor myConceptMotorTable = createDescriptorForMotorTable();
  /*package*/ final ConceptDescriptor myConceptProductionWell = createDescriptorForProductionWell();
  /*package*/ final ConceptDescriptor myConceptPumpingUnit = createDescriptorForPumpingUnit();
  /*package*/ final ConceptDescriptor myConceptSimpleJavaScripts = createDescriptorForSimpleJavaScripts();
  /*package*/ final ConceptDescriptor myConceptSingleLineComment = createDescriptorForSingleLineComment();
  /*package*/ final ConceptDescriptor myConceptSupplies = createDescriptorForSupplies();
  /*package*/ final ConceptDescriptor myConceptSurfaceProperties = createDescriptorForSurfaceProperties();
  /*package*/ final ConceptDescriptor myConceptTask = createDescriptorForTask();
  /*package*/ final ConceptDescriptor myConceptVersioning = createDescriptorForVersioning();
  /*package*/ final ConceptDescriptor myConceptWell = createDescriptorForWell();
  /*package*/ final ConceptDescriptor myConceptWellPersonel = createDescriptorForWellPersonel();
  /*package*/ final ConceptDescriptor myConceptWorker = createDescriptorForWorker();
  /*package*/ final ConceptDescriptor myConceptWorkersTable = createDescriptorForWorkersTable();
  /*package*/ final EnumerationDescriptor myEnumerationActivityType = new EnumerationDescriptor_ActivityType();
  /*package*/ final EnumerationDescriptor myEnumerationLengthUnits = new EnumerationDescriptor_LengthUnits();
  /*package*/ final EnumerationDescriptor myEnumerationMotorType = new EnumerationDescriptor_MotorType();
  /*package*/ final EnumerationDescriptor myEnumerationPumpUnitGeometry = new EnumerationDescriptor_PumpUnitGeometry();
  /*package*/ final EnumerationDescriptor myEnumerationRoles = new EnumerationDescriptor_Roles();
  /*package*/ final EnumerationDescriptor myEnumerationRotation = new EnumerationDescriptor_Rotation();
  /*package*/ final EnumerationDescriptor myEnumerationTempUnits = new EnumerationDescriptor_TempUnits();
  /*package*/ final EnumerationDescriptor myEnumerationVolumeUnits = new EnumerationDescriptor_VolumeUnits();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.extendedLanguage(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, "com.mbeddr.core.base");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActivitySchedule, myConceptActivityTable, myConceptCasingProperties, myConceptCoordinates, myConceptDate, myConceptDepositWell, myConceptDownhole, myConceptFluid, myConceptHorizontalWell, myConceptInjectionWell, myConceptInnerPesonel, myConceptLengthWrapper, myConceptMachinery, myConceptMetadata, myConceptMotor, myConceptMotorTable, myConceptProductionWell, myConceptPumpingUnit, myConceptSimpleJavaScripts, myConceptSingleLineComment, myConceptSupplies, myConceptSurfaceProperties, myConceptTask, myConceptVersioning, myConceptWell, myConceptWellPersonel, myConceptWorker, myConceptWorkersTable);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ActivitySchedule:
        return myConceptActivitySchedule;
      case LanguageConceptSwitch.ActivityTable:
        return myConceptActivityTable;
      case LanguageConceptSwitch.CasingProperties:
        return myConceptCasingProperties;
      case LanguageConceptSwitch.Coordinates:
        return myConceptCoordinates;
      case LanguageConceptSwitch.Date:
        return myConceptDate;
      case LanguageConceptSwitch.DepositWell:
        return myConceptDepositWell;
      case LanguageConceptSwitch.Downhole:
        return myConceptDownhole;
      case LanguageConceptSwitch.Fluid:
        return myConceptFluid;
      case LanguageConceptSwitch.HorizontalWell:
        return myConceptHorizontalWell;
      case LanguageConceptSwitch.InjectionWell:
        return myConceptInjectionWell;
      case LanguageConceptSwitch.InnerPesonel:
        return myConceptInnerPesonel;
      case LanguageConceptSwitch.LengthWrapper:
        return myConceptLengthWrapper;
      case LanguageConceptSwitch.Machinery:
        return myConceptMachinery;
      case LanguageConceptSwitch.Metadata:
        return myConceptMetadata;
      case LanguageConceptSwitch.Motor:
        return myConceptMotor;
      case LanguageConceptSwitch.MotorTable:
        return myConceptMotorTable;
      case LanguageConceptSwitch.ProductionWell:
        return myConceptProductionWell;
      case LanguageConceptSwitch.PumpingUnit:
        return myConceptPumpingUnit;
      case LanguageConceptSwitch.SimpleJavaScripts:
        return myConceptSimpleJavaScripts;
      case LanguageConceptSwitch.SingleLineComment:
        return myConceptSingleLineComment;
      case LanguageConceptSwitch.Supplies:
        return myConceptSupplies;
      case LanguageConceptSwitch.SurfaceProperties:
        return myConceptSurfaceProperties;
      case LanguageConceptSwitch.Task:
        return myConceptTask;
      case LanguageConceptSwitch.Versioning:
        return myConceptVersioning;
      case LanguageConceptSwitch.Well:
        return myConceptWell;
      case LanguageConceptSwitch.WellPersonel:
        return myConceptWellPersonel;
      case LanguageConceptSwitch.Worker:
        return myConceptWorker;
      case LanguageConceptSwitch.WorkersTable:
        return myConceptWorkersTable;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationActivityType, myEnumerationLengthUnits, myEnumerationMotorType, myEnumerationPumpUnitGeometry, myEnumerationRoles, myEnumerationRotation, myEnumerationTempUnits, myEnumerationVolumeUnits);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActivitySchedule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "ActivitySchedule", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8df986606L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8076358177615537670");
    b.version(3);
    b.associate("worker", 0x7014fcf8dfabe79fL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x42bc18f0f6f96090L).optional(true).origin("8076358177616816031").done();
    b.aggregate("tasks", 0x7014fcf8dfabe055L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8df9866aaL).optional(true).ordered(true).multiple(true).origin("8076358177616814165").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActivityTable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "ActivityTable", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x356dc6983436c349L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/3849951613484974921");
    b.version(3);
    b.aggregate("activities", 0x356dc6983436c34aL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8df986606L).optional(true).ordered(true).multiple(true).origin("3849951613484974922").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCasingProperties() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "CasingProperties", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x6e825ec7df0e6c14L);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/7963031303678225428");
    b.version(3);
    b.property("pressure", 0x6e825ec7df0e6c16L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225430").done();
    b.property("cut", 0x6e825ec7df0e6c18L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225432").done();
    b.property("surfaceFluidLevel", 0x6e825ec7df0e6c1cL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225436").done();
    b.property("pumpFluidLevel", 0x6e825ec7df0e6c21L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225441").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCoordinates() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Coordinates", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31147cce5L);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166660837");
    b.version(3);
    b.property("x", 0x14a09e31147cce6L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("92897613166660838").done();
    b.property("y", 0x14a09e31147cce8L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("92897613166660840").done();
    b.property("z", 0x14a09e31147ccebL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("92897613166660843").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Date", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8dfab7956L);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8076358177616787798");
    b.version(3);
    b.property("day", 0x7014fcf8dfab7975L).type(PrimitiveTypeId.STRING).origin("8076358177616787829").done();
    b.property("month", 0x7014fcf8dfab798bL).type(PrimitiveTypeId.STRING).origin("8076358177616787851").done();
    b.property("year", 0x7014fcf8dfab79acL).type(PrimitiveTypeId.STRING).origin("8076358177616787884").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDepositWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "DepositWell", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x6f377013607a9598L);
    b.class_(false, false, true);
    // extends: WellLanguage.structure.Well
    b.super_(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8013997290454422936");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDownhole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Downhole", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b0a1L);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784673");
    b.version(3);
    b.property("topPerforation", 0x7e18434ae3091f4fL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("9086086237135642447").done();
    b.property("bottomPerforation", 0x7e18434ae3091f52L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("9086086237135642450").done();
    b.property("anchor", 0x7e18434ae3091f56L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("9086086237135642454").done();
    b.property("plugBackTotalDepth", 0x7e18434ae3091f5cL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("9086086237135642460").done();
    b.property("pumpMeasuredDepth", 0x7e18434ae3091f62L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("9086086237135642466").done();
    b.property("pumpVerticalMeasuredDepth", 0x7e18434ae3091f68L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("9086086237135642472").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFluid() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Fluid", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149cc8dL);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166791821");
    b.version(3);
    b.property("oil", 0x6e825ec7df0e6bf2L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225394").done();
    b.property("water", 0x6e825ec7df0e6bf4L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225396").done();
    b.property("gas", 0x6e825ec7df0e6bfbL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225403").done();
    b.property("pressure", 0x6e825ec7df0e6bffL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225407").done();
    b.property("gradient", 0x6e825ec7df0e6c05L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225413").done();
    b.property("temperature", 0x6e825ec7df0e6c0cL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("7963031303678225420").done();
    b.associate("well", 0x5a2ab5393abe1325L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL).optional(true).origin("6497204669838660389").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHorizontalWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "HorizontalWell", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x6f377013607d7d5eL);
    b.class_(false, false, true);
    // extends: WellLanguage.structure.Well
    b.super_(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8013997290454613342");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInjectionWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "InjectionWell", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7c11e1450a8fc74aL);
    b.class_(false, false, true);
    // extends: WellLanguage.structure.Well
    b.super_(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8940174421953333066");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInnerPesonel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "InnerPesonel", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a398ae7ea8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691544833704");
    b.version(3);
    b.property("id", 0x394a28a398aeb49cL).type(PrimitiveTypeId.STRING).origin("4128156691544847516").done();
    b.property("description", 0x394a28a398aeb49eL).type(PrimitiveTypeId.STRING).origin("4128156691544847518").done();
    b.property("role", 0x394a28a398aeb4a1L).type(MetaIdFactory.dataTypeId(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x42bc18f0f70d7491L)).origin("4128156691544847521").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLengthWrapper() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "LengthWrapper", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a3989f2566L);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691543827814");
    b.version(3);
    b.property("length", 0x394a28a3989f2567L).type(MetaIdFactory.dataTypeId(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a3988c6c2cL)).origin("4128156691543827815").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMachinery() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Machinery", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x1b88da8d75554533L);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/1984075936950469939");
    b.version(3);
    b.alias("machinery");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMetadata() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Metadata", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a399072b4fL);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691550645071");
    b.version(3);
    b.property("autors", 0x394a28a399072b9bL).type(PrimitiveTypeId.STRING).origin("4128156691550645147").done();
    b.property("version", 0x394a28a399072bbbL).type(PrimitiveTypeId.STRING).origin("4128156691550645179").done();
    b.property("metaDescription", 0x394a28a399072c09L).type(PrimitiveTypeId.STRING).origin("4128156691550645257").done();
    b.property("date", 0x394a28a399072c76L).type(PrimitiveTypeId.STRING).origin("4128156691550645366").done();
    b.property("versioning", 0x394a28a399072ca8L).type(PrimitiveTypeId.STRING).origin("4128156691550645416").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMotor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Motor", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b081L);
    b.class_(false, false, false);
    // extends: WellLanguage.structure.Machinery
    b.super_(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x1b88da8d75554533L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784641");
    b.version(3);
    b.property("manufacturer", 0x14a09e31149b083L).type(PrimitiveTypeId.STRING).origin("92897613166784643").done();
    b.property("type", 0x14a09e31149b09bL).type(MetaIdFactory.dataTypeId(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b090L)).origin("92897613166784667").done();
    b.property("inertia", 0x14a09e31149b085L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("92897613166784645").done();
    b.property("maxAmp", 0x14a09e31149b089L).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("92897613166784649").done();
    b.associate("well", 0x5a2ab5393ac55604L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL).optional(true).origin("6497204669839136260").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMotorTable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "MotorTable", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x5a2ab5393ab9e7cfL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/6497204669838387151");
    b.version(3);
    b.aggregate("motors", 0x5a2ab5393ab9e7d0L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b081L).optional(true).ordered(true).multiple(true).origin("6497204669838387152").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProductionWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "ProductionWell", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x6f377013607d7d5cL);
    b.class_(false, false, true);
    // extends: WellLanguage.structure.Well
    b.super_(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8013997290454613340");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPumpingUnit() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "PumpingUnit", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b05dL);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/92897613166784605");
    b.version(3);
    b.property("id", 0x14a09e31149b062L).type(PrimitiveTypeId.STRING).origin("92897613166784610").done();
    b.property("unitGeo", 0x14a09e31149b064L).type(MetaIdFactory.dataTypeId(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b069L)).origin("92897613166784612").done();
    b.property("description", 0x14a09e31149b07bL).type(PrimitiveTypeId.STRING).origin("92897613166784635").done();
    b.associate("well", 0x5a2ab5393ac55606L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL).optional(true).origin("6497204669839136262").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSimpleJavaScripts() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "SimpleJavaScripts", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a398ee7638L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x617d88a37ecb2fa8L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691549025848");
    b.version(3);
    b.aggregate("statements", 0x394a28a398ee7812L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L).optional(true).ordered(true).multiple(false).origin("4128156691549026322").done();
    b.aggregate("methods", 0x394a28a398ee787dL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x6c6b6a1e379f9408L).optional(true).ordered(true).multiple(true).origin("4128156691549026429").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSingleLineComment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "SingleLineComment", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x356dc698340631e9L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.SingleLineComment
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x57d533a7af15ed3aL);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/3849951613481791977");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSupplies() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Supplies", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x356dc6983460dd2eL);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/3849951613487734062");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSurfaceProperties() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "SurfaceProperties", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7e18434ae3095a34L);
    b.class_(false, false, false);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/9086086237135657524");
    b.version(3);
    b.property("stroke", 0x7e18434ae3095a3cL).type(MetaIdFactory.dataTypeId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x120aa230057L)).origin("9086086237135657532").done();
    b.property("rotation", 0x7e18434ae3095a41L).type(MetaIdFactory.dataTypeId(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7e18434ae3095a46L)).origin("9086086237135657537").done();
    b.associate("well", 0x5a2ab5393ac55608L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL).optional(true).origin("6497204669839136264").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTask() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Task", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8df9866aaL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/8076358177615537834");
    b.version(3);
    b.property("description", 0x7014fcf8dfab7a68L).type(PrimitiveTypeId.STRING).origin("8076358177616788072").done();
    b.property("activityType", 0x7014fcf8dfabdf86L).type(MetaIdFactory.dataTypeId(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8dfabdef1L)).origin("8076358177616813958").done();
    b.associate("well", 0x7014fcf8dfabdec5L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL).optional(true).origin("8076358177616813765").done();
    b.aggregate("startDate", 0x7014fcf8dfab7abeL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8dfab7956L).optional(true).ordered(true).multiple(false).origin("8076358177616788158").done();
    b.aggregate("endDate", 0x7014fcf8dfc23066L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8dfab7956L).optional(true).ordered(true).multiple(false).origin("8076358177618276454").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVersioning() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Versioning", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a399072dc8L);
    b.class_(false, false, true);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4128156691550645704");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Well", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.parent(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x617d88a37ecb2fa8L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/5154331406846477612");
    b.version(3);
    b.property("generalDescription", 0x42bc18f0f6edd996L).type(PrimitiveTypeId.STRING).origin("4808745925338847638").done();
    b.associate("worker", 0x7014fcf8dfb6e6a5L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x42bc18f0f6f96090L).optional(true).origin("8076358177617536677").done();
    b.aggregate("coordinates", 0x6f377013607a958cL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31147cce5L).optional(true).ordered(true).multiple(false).origin("8013997290454422924").done();
    b.aggregate("downholeProps", 0x6f377013607d7d60L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b0a1L).optional(true).ordered(true).multiple(false).origin("8013997290454613344").done();
    b.aggregate("fluidProps", 0x6f377013607d7d63L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149cc8dL).optional(true).ordered(true).multiple(false).origin("8013997290454613347").done();
    b.aggregate("pumpUnitProps", 0x51643a35ce93a256L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b05dL).optional(true).ordered(true).multiple(true).origin("5864876617516687958").done();
    b.aggregate("surfaceProps", 0x394a28a398fefdc7L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7e18434ae3095a34L).optional(true).ordered(true).multiple(false).origin("4128156691550109127").done();
    b.aggregate("casingProps", 0x394a28a398fefd14L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x6e825ec7df0e6c14L).optional(true).ordered(true).multiple(false).origin("4128156691550108948").done();
    b.aggregate("motorProps", 0x51643a35ce934d39L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x14a09e31149b081L).optional(true).ordered(true).multiple(true).origin("5864876617516666169").done();
    b.aggregate("machinery", 0x356dc6983421400bL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x1b88da8d75554533L).optional(true).ordered(true).multiple(true).origin("3849951613483565067").done();
    b.aggregate("supplies", 0x356dc69834620e0aL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x356dc6983460dd2eL).optional(true).ordered(true).multiple(false).origin("3849951613487812106").done();
    b.aggregate("personel", 0x356dc69834620e13L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x356dc6983460dd2dL).optional(true).ordered(true).multiple(true).origin("3849951613487812115").done();
    b.aggregate("urgentTasks", 0x356dc69834620e1dL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8df9866aaL).optional(true).ordered(true).multiple(false).origin("3849951613487812125").done();
    b.aggregate("customMethods", 0x394a28a398bb8f32L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x6c6b6a1e379f9408L).optional(true).ordered(true).multiple(true).origin("4128156691545689906").done();
    b.aggregate("customStatements", 0x394a28a398dea8acL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L).optional(true).ordered(true).multiple(false).origin("4128156691547990188").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWellPersonel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "WellPersonel", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x356dc6983460dd2dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/3849951613487734061");
    b.version(3);
    b.associate("tasks", 0x394a28a3990707fcL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x7014fcf8df986606L).optional(true).origin("4128156691550636028").done();
    b.aggregate("personel", 0x394a28a398adf6c6L).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x394a28a398ae7ea8L).optional(true).ordered(true).multiple(true).origin("4128156691544798918").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWorker() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "Worker", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x42bc18f0f6f96090L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/4808745925339603088");
    b.version(3);
    b.property("id", 0xa279d96fed31737L).type(PrimitiveTypeId.INTEGER).origin("731726736316897079").done();
    b.property("description", 0x42bc18f0f6f96093L).type(PrimitiveTypeId.STRING).origin("4808745925339603091").done();
    b.property("role", 0x42bc18f0f6f96095L).type(MetaIdFactory.dataTypeId(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x42bc18f0f70d7491L)).origin("4808745925339603093").done();
    b.associate("well", 0x7014fcf8df7c10edL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x4787dd1b0fb9452cL).optional(true).origin("8076358177613680877").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWorkersTable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WellLanguage", "WorkersTable", 0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0xa279d96fed31899L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11041e4c-db17-433f-9948-c6a16ce7eaf6(WellLanguage.structure)/731726736316897433");
    b.version(3);
    b.aggregate("workers", 0x21c7e9a955f9c70cL).target(0x1f9e61a5590e4e5eL, 0x9835cf0a05fde422L, 0x42bc18f0f6f96090L).optional(true).ordered(true).multiple(true).origin("2434171037118220044").done();
    return b.create();
  }
}
